movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')

]

movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)
def detail(request,id):
    movie=Movie.objects.get(id=id)
    return render(request,'detail.html',{'movie':movie})

def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter your name"><br>
  <input type="text" name="desc" placeholder="Enter the movie description"><br>
  <input type="text" name="year" placeholder="Enter your movie year"><br>
  <input type="file" name="img"><br>
  <input type="submit">
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'movie_style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="">
    Online Movie Store
  </a>
  {% csrf_token %}
  <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'movieapp:add_movie' %}">Add Movie</a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}


<form method="POST">
  {% csrf_token %}
  are you want to delete this movie?
  <input type="submit">
</form>

{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" height="400" width="400" style="padding:6px;">
        </div>
<div class="col-md-6">
    <h2>{{movie.name}}</h2>
    <h4>{{movie.desc}}</h4>
    <h6>{{movie.year}}</h6>
    <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a><br>
</div>
    </div>
</div>

{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block body %}
<style>
    .card {
        border: 1px solid #ddd;
        border-radius: 10px;
        margin-bottom: 20px;
        transition: box-shadow 0.3s;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.1);
        background-color: #fff;
    }
    
    .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
    }

    .card-img-top {
        width: 100%;
        height: 200px;
        object-fit: cover;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
    }

    .card-body {
        padding: 20px;
    }

    .card-title {
        font-size: 20px;
        font-weight: bold;
        margin-bottom: 15px;
        color: #333;
    }

    .card-text {
        font-size: 16px;
        color: #555;
    }

    .btn-primary {
        background-color: #1ed856;
        border-color: #1ed856;
        color: #fff;
        padding: 10px 20px;
        text-decoration: none;
        border-radius: 25px;
        transition: background-color 0.3s;
    }

    .btn-primary:hover {
        background-color: #0056b3;
        border-color: #0056b3;
    }
</style>

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-4">
            <div class="card">
                <img class="card-img-top" src="{{i.img.url}}" alt="{{i.name}}">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.desc}}</p>
                    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Movie Info</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}